---
- hosts: nfs-clients
  become: yes
  tasks:
    - name: Ensure NFS common is installed.
      apt: name=nfs-common state=present update_cache=yes

    - name: Create mountable dir
      file: path=/nfs state=directory mode=777 owner=root group=root

    - name: set mountpoints
      # mount: name=/nfs src={{hostvars[groups['nfs_server'][0]]['ansible_eth0']['ipv4']['address']}}:/share fstype=nfs opts=defaults,nobootwait dump=0 passno=2 state=mounted
      # mount: name=/nfs src=192.168.0.2:/var/nfs/general fstype=nfs opts=defaults,nobootwait dump=0 passno=2 state=mounted
      mount: name=/nfs src=192.168.0.2:/var/nfs/general fstype=nfs state=mounted

      #/var/nfs/general /nfs/general